DROP TABLE IF EXISTS RECORDS;

CREATE TABLE RECORDS(
  ID INT AUTO_INCREMENT,
  PSEUDO VARCHAR(25),
  SCORE INT,

  PRIMARY KEY (id)
);

INSERT INTO RECORDS VALUES (NULL, 'Nohan', 200);
INSERT INTO RECORDS VALUES (NULL, 'Tom', 10);
INSERT INTO RECORDS VALUES (NULL, 'Bilal', 2000);
